# Module manifest for module 'psWarpTerminal'
# Generated by: skatterbrainz
# Generated on: 2/25/2026

@{
RootModule = 'psWarpTerminal.psm1'
ModuleVersion = '1.1.0'
# CompatiblePSEditions = @()
GUID = '455614f9-bb6e-4639-9410-4ed287a61c5f'
Author = 'skatterbrainz'
# CompanyName = ''
Copyright = '(c) 2026 skatterbrainz. All rights reserved.'
Description = 'PowerShell wrapper for the Warp Terminal (Oz) CLI'
PowerShellVersion = '5.1'
# PowerShellHostName = ''
# PowerShellHostVersion = ''
# DotNetFrameworkVersion = ''
# ClrVersion = ''
# ProcessorArchitecture = ''
# RequiredModules = @()
# RequiredAssemblies = @()
# ScriptsToProcess = @()
# TypesToProcess = @()
# FormatsToProcess = @()
# NestedModules = @()
FunctionsToExport = @('Get-*', 'New-*', 'Set-*', 'Remove-*', 'Invoke-*', 'Connect-*', 'Disconnect-*', 'Suspend-*', 'Resume-*', 'Clear-*')
CmdletsToExport = '*'
VariablesToExport = '*'
AliasesToExport = '*'
# DscResourcesToExport = @()
# ModuleList = @()
# FileList = @()
PrivateData = @{
    PSData = @{
        Tags = @('Warp', 'WarpTerminal', 'Oz', 'Agent', 'CLI', 'LLM','AI', 'Terminal', 'skatterbrainz')
        LicenseUri = 'https://github.com/Skatterbrainz/psWarpTerminal/blob/main/LICENSE'
        ProjectUri = 'https://github.com/Skatterbrainz/psWarpTerminal'
        IconUri = 'https://github.com/user-attachments/assets/afd49cd8-ebc4-4511-a10f-53ac308b301a'
        # ReleaseNotes = ''
        # Prerelease = ''
        RequireLicenseAcceptance = $false
        # ExternalModuleDependencies = @()
    } # End of PSData hashtable
} # End of PrivateData hashtable
# HelpInfoURI = ''
# DefaultCommandPrefix = ''
}