# Module manifest for module 'psWarpTerminal'
# Generated by: David Stein
# Generated on: 8/4/2026

@{
RootModule = '.\psWarpTerminal.psm1'
ModuleVersion = '1.6.0'
# CompatiblePSEditions = @()
GUID = '455614f9-bb6e-4639-9410-4ed287a61c5f'
Author = 'skatterbrainz'
# CompanyName = ''
Copyright = '(c) 2026 David Stein. All rights reserved.'
Description = 'PowerShell wrapper for the Warp Terminal (Oz) CLI'
PowerShellVersion = '5.1'
# PowerShellHostName = ''
# PowerShellHostVersion = ''
# DotNetFrameworkVersion = ''
# ClrVersion = ''
# ProcessorArchitecture = ''
# RequiredModules = @()
# RequiredAssemblies = @()
# ScriptsToProcess = @()
# TypesToProcess = @()
# FormatsToProcess = @()
# NestedModules = @()
FunctionsToExport = @(
    'Clear-WarpAgentContext',
    'Connect-Warp',
    'Disconnect-Warp',
    'Get-WarpAgent',
    'Get-WarpAgentContext',
    'Get-WarpAgentProfile',
    'Get-WarpApiKey',
    'Get-WarpArtifact',
    'Get-WarpEnvironment',
    'Get-WarpEnvironmentImage',
    'Get-WarpFederatedToken',
    'Get-WarpIntegration',
    'Get-WarpMcp',
    'Get-WarpMemory',
    'Get-WarpMemoryStore',
    'Get-WarpModel',
    'Get-WarpRun',
    'Get-WarpRunConversation',
    'Get-WarpRunMessage',
    'Get-WarpRunner',
    'Get-WarpSchedule',
    'Get-WarpSecret',
    'Get-WarpSettings',
    'Get-WarpSkill',
    'Get-WarpWhoAmI',
    'Invoke-WarpAgent',
    'New-WarpAgent',
    'New-WarpApiKey',
    'New-WarpEnvironment',
    'New-WarpIntegration',
    'New-WarpMemory',
    'New-WarpRunner',
    'New-WarpSchedule',
    'New-WarpSecret',
    'Remove-WarpAgent',
    'Remove-WarpApiKey',
    'Remove-WarpEnvironment',
    'Remove-WarpMemory',
    'Remove-WarpRunner',
    'Remove-WarpSchedule',
    'Remove-WarpSecret',
    'Resume-WarpSchedule',
    'Save-WarpArtifact',
    'Send-WarpRunMessage',
    'Set-WarpAgent',
    'Set-WarpEnvironment',
    'Set-WarpIntegration',
    'Set-WarpMemory',
    'Set-WarpMemoryStore',
    'Set-WarpRunMessage',
    'Set-WarpRunner',
    'Set-WarpSchedule',
    'Set-WarpSecret',
    'Suspend-WarpSchedule',
    'Watch-WarpRunMessage'
)
CmdletsToExport = '*'
VariablesToExport = '*'
AliasesToExport = '*'
# DscResourcesToExport = @()
# ModuleList = @()
# FileList = @()
PrivateData = @{
    PSData = @{
        Tags = @('Warp', 'WarpTerminal', 'Oz', 'Agent', 'CLI', 'LLM','AI', 'Terminal', 'skatterbrainz')
        LicenseUri = 'https://github.com/Skatterbrainz/psWarpTerminal/blob/main/LICENSE'
        ProjectUri = 'https://github.com/Skatterbrainz/psWarpTerminal'
        # IconUri = ''
        # ReleaseNotes = ''
        # Prerelease = ''
        RequireLicenseAcceptance = $false
        # ExternalModuleDependencies = @()
    } # End of PSData hashtable
} # End of PrivateData hashtable
# HelpInfoURI = ''
# DefaultCommandPrefix = ''
}